### ISSUE TITLE
ZD new banner stopping script

### ISSUE THREAD

**Issue by brentaddis** [bot779/ruckusconf#3]
Hi,

Our zone director seems to throw up a script before login rendering the script inoperable. Is there anything that can be done to work around this?

root@commie:/usr/local/bin# ./ruckusconf.sh --enable --command "show config" hostname
spawn ssh admin@zd.commodore.net.nz

Please login: admin
Password: 
Warning, you are logging into device for authorized user only. If you are not an authorized user, please click Quit; otherwise click Continue to login.
[Quit:input 'q', Continue:press 'Enter']:extra characters after close-quote
    while executing
"sttyechoexit 'Timed out waiting for "'"$"
    invoked from within
"expect {
    $prompt { set aprompt 0 }
    "sername:" {
          set aprompt 2
          if { "$username" == "" } {
            #stty -echo
         ..."
    ("foreach" body line 46)
    invoked from within
"foreach device $devlist {
set commandlist $originalcommandlist
set prompt $firstprompt
# if { $debug eq "true" } {
# send_user "apasswd is $apasswd..."

```
("while" body line 106)
invoked from within
```

"while { $continueloop == "true" } {
  if { $loopprog == "" } {
    set continueloop false
  } else {
    if { [ catch {exec $loopprog} msg ] } {
     ..."
    (file "./ruckusconf.sh" line 320)
root@commie:/usr/local/bin#

**Comment by bot779** [comment]
The latest update should have fixed that.
(but I don't use that login_banner feature here so I couldn't test it)

I hard coded the string/phrase "Continue:press 'Enter']:" into the script.
Hopefully that's something that's common to all Ruckus banner messages and not just related to the message on your box.
Otherwise, other people will have to change the script to make that feature work for them or I'll have to add another option to specify what the banner prompt (quit or don't quit) message should look like.
